DO $$
BEGIN
  ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'QUALIFIED' AFTER 'CONTACTED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'PROPOSAL_SENT' AFTER 'QUALIFIED';
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;
